# Generated by go2rpm 1
%bcond_without check

# https://github.com/issue9/assert
%global goipath         github.com/issue9/assert
Version:                1.3.4

%gometa

%global common_description %{expand:
Go 语言 assert 断言函数.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Go 语言 assert 断言函数

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sun Jan 26 12:06:26 CET 2020 Marcel Metz <mmetz@adrian-broher.net> - 1.3.4-1
- Initial package
